import { SectionShell } from "@/components/tools/shared/layout/SectionShell";
import { RevealText } from "@/components/tools/shared/motion/RevealText";
import { GlassCard } from "@/components/tools/shared/ui/GlassCard";
import { Badge } from "@/components/tools/shared/ui/Badge";
import {
  OrganizationIcon,
  WebsiteIcon,
  BreadcrumbIcon,
  ArticleIcon,
  FaqIcon,
  LocalBusinessIcon,
  ProductIcon,
  SoftwareAppIcon,
  PersonIcon,
  EventIcon,
  ReviewIcon,
  HowToIcon,
} from "@/components/tools/shared/icons/SchemaIcons";

// Exactly 12 (a clean 4x3 grid) — VideoObject/Recipe are still generated by
// the tool, called out in the closing tile instead of padding an orphan row.
const TYPES = [
  { icon: OrganizationIcon, name: "Organization", badge: "Google-eligible" },
  { icon: WebsiteIcon, name: "WebSite", badge: "AI-cited" },
  { icon: BreadcrumbIcon, name: "BreadcrumbList", badge: "Google-eligible" },
  { icon: ArticleIcon, name: "Article", badge: "Google-eligible" },
  { icon: FaqIcon, name: "FAQPage", badge: "AI-cited" },
  { icon: LocalBusinessIcon, name: "LocalBusiness", badge: "Google-eligible" },
  { icon: ProductIcon, name: "Product", badge: "Google-eligible" },
  { icon: SoftwareAppIcon, name: "SoftwareApplication", badge: "Google-eligible" },
  { icon: PersonIcon, name: "Person", badge: "AI-cited" },
  { icon: EventIcon, name: "Event", badge: "Google-eligible" },
  { icon: ReviewIcon, name: "Review", badge: "Google-eligible" },
  { icon: HowToIcon, name: "HowTo", badge: "AI-cited" },
];

export function CoverageMap() {
  return (
    <SectionShell className="border-t border-foreground/10 py-28 md:py-36">
      <div className="mb-16 max-w-2xl">
        <p className="mb-4 font-body text-xs uppercase tracking-[0.2em] text-primary md:whitespace-nowrap">
          Full coverage
        </p>
        <h2 className="font-display text-4xl leading-tight text-foreground md:text-5xl">
          <RevealText text="Every schema type that matters, done right." />
        </h2>
      </div>

      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        {TYPES.map((type) => (
          <GlassCard
            key={type.name}
            className="group flex flex-col gap-4 p-5 transition-transform duration-300 hover:-translate-y-1"
          >
            <type.icon className="h-6 w-6 text-foreground/70 transition-colors group-hover:text-primary" />
            <p className="font-body text-sm text-foreground">{type.name}</p>
            <Badge tone={type.badge === "AI-cited" ? "primary" : "outline"} className="w-fit">
              {type.badge}
            </Badge>
          </GlassCard>
        ))}
      </div>

      <p className="mt-6 font-body text-sm text-foreground/40">
        Plus VideoObject and Recipe — every type ships with the same required/recommended field checklist.
      </p>
    </SectionShell>
  );
}
